name: PR test

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          ${{ runner.os }}-
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      run: ./gradlew testDebug --no-daemon
    - name: Archive test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-results
        path: "yoti-sdk/build/reports/tests/"
